### ISSUE TITLE
Can't type in browser console [WIN]

### ISSUE THREAD

**Issue by seanvree** [sourcelair/xterm.js#1070]
## Details
- Chome Version 62.0.3202.62 (Official Build) (64-bit)
- OS version: Windows 10 X64 1709
- xterm.js version:  2.9.2

### Issue:

When I try to access via a browser served by my webserver (IIS), I get a blank console, but I can't type anything, no errors in the browser console  See Screenshot below. 

If I launch via NPM, "set PORT=8300&&npm run dev" I can access the demo site via localhost:8300 just fine.  

Any idea what I'm doing wrong here?

![xterm](https://user-images.githubusercontent.com/8906637/31782589-407dde06-b4b0-11e7-8737-b76643e4e74f.PNG)

Here is my index.html:

```
<!doctype html>
<html>

<head>
    <title>xterm.js demo</title>
    <link rel="stylesheet" href="/xterm/build/xterm.css" />
    <link rel="stylesheet" href="/xterm/build/addons/fullscreen/fullscreen.css" />
    <link rel="stylesheet" href="/xterm/build/style.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.1.1/es6-promise.auto.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fetch/1.0.0/fetch.min.js"></script>
    <script src="/xterm/build/xterm.js"></script>
    <script src="/xterm/build/addons/attach/attach.js"></script>
    <script src="/xterm/build/addons/fit/fit.js"></script>
    <!-- <script src="/xterm/build/addons/fullscreen/fullscreen.js"></script> -->
    <script src="/xterm/build/addons/search/search.js"></script>
</head>

<body>

    <div id="terminal"></div>
    <script>
        var term = new Terminal();
        term.open(document.getElementById('terminal'));
        term.write('\033[1;3;31mxterm.js\033[0m $ ')
    </script>

    <div id="terminal-container"></div>


</body>

</html>
```

**Comment by parisk** [comment]
@seanvree by most chances this is an issue at the "transport layer" of your application. I would suggest you inspecting the WebSocket connection in the "Network" tab in the developer tools of Chrome.

Since this is not actually a library issue, I am closing this issue now.

I suggest you asking a new question at https://stackoverflow.com and add the [`xtermjs`](https://stackoverflow.com/tags/xtermjs/), [`iis`](https://stackoverflow.com/tags/iis/) and the [`websocket`](https://stackoverflow.com/tags/websocket) tags.

We keep an eye on the xtermjs tag ourselves, but most probably this has to do more with IIS.

**Comment by seanvree** [comment]
@parisk  yeah, I have no doubt it's an IIS issue as well, Just wondering if anyone had any tips.  

Do you by chance KNOW if this works with IIS?

I'll check out SO.  Thanks!

**Comment by parisk** [comment]
@seanvree I have no idea about IIS in general, but if it's implementing the WebSocket protocol (I bet it does) it should work just fine.

**Comment by seanvree** [comment]
@parisk thanks, I'll dig into it.
