### ISSUE TITLE
Firefox: Deleting from context menu works.

### ISSUE THREAD

**Issue by runarberg** [sourcelair/xterm.js#116]
Selecting a text on firefox, and right clicking, will open a context menu (as expected), the menu contains `delete` which deletes any text from the terminal. I'm sure that is not supposed to happen.

**Comment by runarberg** [comment]
![xterm-delete](https://cloud.githubusercontent.com/assets/3984600/15971903/06b106aa-2f2b-11e6-9e6b-68d694cf15e5.png)

**Comment by parisk** [comment]
Unfortunately, it seems that it is not possible to stop this behavior, if we would like to keep right-click paste: http://stackoverflow.com/a/8736770.

The only hack that I can think of is disabling `contentEditable` when there is selected text in the terminal, since it won't make any sense to paste on a selection and the side effect would be removing all content-changing actions from the context menu as well (including Delete).

**Comment by Tyriar** [comment]
We no longer use `contenteditable` so this is fixed
