### ISSUE TITLE
alt+clicking messes up an ncurses app (Weechat IRC Client)

### ISSUE THREAD

**Issue by stereokai** [sourcelair/xterm.js#1410]
## Details
- Browser and browser version: Chrome 58, Chrome 59, Edge (latest)
- OS version: Windows 10 Pro
- xterm.js version: ^3.3.0

### Steps to reproduce
1. Use any `xterm.js` based terminal: VSCode, Hyper.js, FluentTerminal
2. Open WSL (Ubuntu on Windows) in terminal
3. Start Weechat - an IRC client
4. If not already enabled, enable mouse using alt+m
4. Use the mouse in the following way:
	1. Try switching channels by alt+clicking on channels' names in the channel list on the left
	2. Try starting a private chat with another user by alt+clicking on the user's name in the users list on the right
5. Observe that instead of performing the desired operations, alt+clicking *anywhere* causes Weechat to cycle between channels sporadically

### How I know it's an `xterm.js` issue
The expected behavior works properly if you open WSL in Windows's own native console (ie ubuntu.exe or wsl.exe - even when starting either from within CMD or Powershell) - so natively, it does work - but wrapped in `xterm.js`, it doesn't.

**Comment by mofux** [comment]
I would have thought that alt+click handling is only enabled while mouse events are disabled, but looking at the code it seems the alt+click handler is always active. 

The reason is that the selection manager gets disabled if mouse events are enabled, but the click handlers still track the mousedown and mouseup events and eventually fire the alt+click handler:
https://github.com/xtermjs/xterm.js/blob/70da7075698e5d91e8ee3162d2f79bdf691f1514/src/SelectionManager.ts#L409

and here:
https://github.com/xtermjs/xterm.js/blob/70da7075698e5d91e8ee3162d2f79bdf691f1514/src/SelectionManager.ts#L594

@npezza93 @Tyriar This behaviour looks like a bug to me - i think we should only enable the alt+click handler if mouse events are disabled. Any thoughts?

**Comment by stereokai** [comment]
@Tyriar @mofux 

Well, in Windows 10 Pro, in all included terminals (ie. CMD, Powershell, and WSL) there is only one cursor all the time and it is the default cursor (I just checked). In xterm.js, there is also only one cursor, and it is the text selection cursor (I checked both in Hyper.js and in VSCode).

To be frank, I think there is something wrong about that behavior - in case there are two modes that is. If xterm.js provides two modes, it should reflect that with the cursor.

I don't mind having a go at a PR, but i'll need to know - what constitutes when mouse events are enabled or disabled? And what exactly do mouse events cover? (ie. what is difference between when they are enabled and disabled).

**Comment by Tyriar** [comment]
xterm's mouse cursor can be the text cursor (non-mouse mode), default (mouse mode) and pointer (hover link). Mouse mode is enabled when the process turns it on using the sequences mentioned in http://invisible-island.net/xterm/ctlseqs/ctlseqs.html (search "mouse mode"). These are not native Windows concepts and what I meant by my comment is that the pty emulation happening in winpty/node-pty might not be setting it. These will probably be improved eventually in node-pty but there's nothing we can do in xterm.js, it defaults to `cursor: default` when the process says turn on mouse mode.

https://github.com/xtermjs/xterm.js/blob/139a2464360d8200cbceaa34e214088216da0de9/src/xterm.css#L129-L136

**Comment by stereokai** [comment]
Thank you for the very detailed reponse concerning how cursors work. How would one go about solving this? Like where to start? Is the problem in x-term or in node/winpty?

**Comment by stereokai** [comment]
@Tyriar With all respect, that issue is a monster! I can work on a PR for this issue, just need some preliminary nudge in the right direction.

**Comment by Tyriar** [comment]
@stereokai yes it is, which is why I'm excited about it getting fixed soon 😄 

I believe mouse mode stuff works just fine, it's just that something is going wrong in the layer on Windows only where it's trying to emulate a Unix terminal. So I don't think there's anything to do other than the major work of addressing https://github.com/Microsoft/vscode/issues/45693
