### ISSUE TITLE
ctrl+up/down don't scroll in zsh

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#181]
1. Launch xterm with bash
2. Open zsh
3. ctrl+up/down scroll history, not scroll

**Comment by parisk** [comment]
Could this be a duplicate of #151?

**Comment by Tyriar** [comment]
I don't think ctrl+up/down is routed to the mouse wheel handler so probably not.

**Comment by apjanke** [comment]
It does look related to #151 and keypad cursor modes. Check out the xterm.js code for [handling the up and down cursor keys](https://github.com/sourcelair/xterm.js/blob/dc17f0d02e65f06a67ea80236aee17575e501a36/src/xterm.js#L2646-L2657).

```
        // up-arrow
        case 38:
          if (this.applicationCursor) {
            result.key = '\x1bOA';
            break;
          }
          if (ev.ctrlKey) {
            result.scrollDisp = -1;
          } else {
            result.key = '\x1b[A';
          }
          break;
```

The application-mode check is done first, and does an early return. The test for the Ctrl key is effectively inside the "normal keypad mode" branch of the logic. This also means that in application cursor keypad mode, the up/down arrow keys are being sent as plain cursor keys, with no modifier. In regular Xterm, modifiers take precedence over keypad mode.

**Comment by jerch** [comment]
Maybe fixed with #200, cant test it myself.

**Comment by parisk** [comment]
@Tyriar could you please test this out, since we merged #200?

**Comment by Tyriar** [comment]
Ctrl+up outputs `;5A` and doesn't scroll, page down outputs `;5B` and doesn't scroll. This is consistent with zsh under `gnome-terminal` so closing as fixed. Note that the scrolling situation is still bad, ctrl+shift+page up/down outputs `;6A` and `6B` with no scroll.

**Comment by jerch** [comment]
> ctrl+shift+page up/down outputs ;6A and 6B with no scroll.

Just installed zsh with and omz and can't reproduce it. I get the following on Ubuntu 14 with my laptop keyboard (same behavior/output for xterm and xterm.js-demo):
<kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>PageUp</kbd> --> jump scroll up
<kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>PageDown</kbd> --> jump scroll down
<kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>ArrowUp</kbd> --> A
<kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>ArrowDown</kbd> --> B

Tested again with gnome-terminal - <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>ArrowUp</kbd> scrolled instead of printing an 'A'. Did you mean PageUp/Down or ArrowUp/Down?

**Comment by apjanke** [comment]
> zsh with and omz

OMZ may change the behavior, because it defines additional key bindings which are not present in default `zsh`. Depending on what plugins you have loaded, it may add bindings for the Ctrl-Up and Ctrl-down character sequences.

> It seems gnome-terminal does not expose Shift+Ctrl+ArrowX to the PTY at all. If you run cat and press the keys xterm will print the corresponding escape sequence while gnome-terminal does not print anything. Might be a bug or a design decision in gnome-terminal.

Design decision. Many terminal emulators and OSes "capture" some modified cursor key strokes and map them to scrolling or other navigation instead of passing them to the pty. This is analogous to the Ctrl-arrow scrolling behavior in xterm.js before #200. When comparing behavior for terminals, you need to check the key binding configuration. In gnome-terminal, look under Edit > Preferences > Shortcuts to see if a modified cursor key combination is mapped to a terminal action instead of being passed along to the PTY. Shift-Ctrl-Up and Shift-Ctrl-Down are [bound to scrolling by default](https://help.gnome.org/users/gnome-terminal/stable/adv-keyboard-shortcuts.html.en) in gnome-terminal.

**Comment by Tyriar** [comment]
ctrl+shift+(most things) seems to be ignored by xterm as they are the only keybindings in vscode that seem to work when the focus is on the integrated terminal.

I'm thinking ctrl+shift+arrow should be handled by xterm.js, not the pty as @apjanke suggests.

**Comment by jerch** [comment]
Still not clear, why ctrl+shift+page up/down outputs ;6A and 6B for you. Seems the browser engine triggers the wrong keycode. Can you check the keycodes for ctrl+shift+page up/down with your keyboard? Do you have some keymapping active on X11 level?

**Comment by Tyriar** [comment]
```
var modifiers = ev.shiftKey << 0 | ev.altKey << 1 | ev.ctrlKey << 2 | ev.metaKey << 3;
// modifiers = 0b0101 = 5
...
result.key = '\x1b[1;' + (modifiers + 1) + 'D';
// result.key = '\x1b[1;6D';
```

**Comment by jerch** [comment]
How about making this customizable?

**Comment by Tyriar** [comment]
Much easier to accomplish now that https://github.com/sourcelair/xterm.js/pull/186 is implemented
