### ISSUE TITLE
Add Information about Webpack usage in the Readme or Docs

### ISSUE THREAD

**Issue by ebertmi** [sourcelair/xterm.js#258]
For webpack users it may be difficult to get xterm running with **es6 modules**. Most libraries use prebuild files on npm that do not need transpiling.
Additionally, a lot of webpack configs in the `internet` exclude the `node_modules` from transpiling, which results in errors with pure es6 modules.

Maybe drop a hint for webpack config like this:

Remove the `exclude` rule for `node_modules` and instead use a custom `include` rule. Just specifying a `include` rule will not work as `exclude` has precedence over `include`. This also avoids complex regular expressions in `exclude` especially with more es modules to come.

``` javascript
...
    loaders: [
      {
        test: /\.js$/,
        include: [
          // We explicitly include all directory, otherwise, this will break
          path.resolve(__dirname, 'YOUR_SRC_DIR'),
          path.resolve(__dirname, 'MAYBE_ANOTHER_ONE'),

          // Add all npm modules that need to be transpiled!
          // Include xterm module
          /\bxterm\b/,
        ],
        loader: 'babel-loader',
        query: {
          presets: ['es2015', 'react']
        }
      }
    ]
...
```

**Comment by parisk** [comment]
Hi @waywaaard es6 modules are not included in a release yet. They will be included in **2.0**, which needs a few things yet to be implemented and it will include transpiled files in the `dist` directory.

A PR including documentation for using with Webpack in the README file would be more than welcome 😊 .

**Comment by waywaaard** [comment]
I guess, then we should wait until the es6 modules are ready and then I can make a PR.

**Comment by Tyriar** [comment]
@parisk should this be on the v2 milestone?

**Comment by parisk** [comment]
That would be great, but as I have no experience with webpack right now, let's leave it outside.

Unless @waywaaard could prepare a PR for https://github.com/xtermjs/xtermjs.org 😊 .

**Comment by waywaaard** [comment]
I can try make one.

**Comment by parisk** [comment]
That would be great. Use branch `xtermjs-2-0` as your base.

**Comment by rdicroce** [comment]
IMO it makes much more sense for users to just use dist/xterm.js rather than trying to configure Webpack with the same transpiler setup xterm has. xterm's transpiler configuration could change over time, so needing to sync it up could be annoying. Also, the dist version is what you'll get if you simply require('xterm') because that's what package.json's main points to.

Using the dist JS works fine, expect for an annoying warning about xterm.js being a pre-built JavaScript file. That warning apparently has something to do with Browserify; see https://github.com/webpack/webpack/issues/1617. Fortunately, xterm has no external dependencies, so you can suppress the warning by adding this to your Webpack config:
```javascript
noParse: [
	/xterm.js$/
]
```

**Comment by parisk** [comment]
I think that documenting how to use the built xterm.js with Webpack at https://github.com/xtermjs/xtermjs.org based in @rdicroce's comment should be enough.

**Comment by Tyriar** [comment]
I'm consolidating all bundling/loadAddon related issues into https://github.com/sourcelair/xterm.js/issues/1018, please comment on that issue if you have thoughts :smiley:
