### ISSUE TITLE
Come up with API for changing settings after initialization

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#271]
Currently there are issues (https://github.com/Microsoft/vscode/issues/11049) when changing settings during runtime since the terminal gets "reset" when application mode is entered and exited. Reset uses `term.options[settingKey]` whereas the actual setting used is `term[key]`. Changing a setting requires both of these to be set.

Current:

```js
xterm.options.cursorBlink = blink;
xterm.cursorBlink = blink;
```

Proposed:

```js
xterm.setOption('cursorBlink', true);
```

Requesting feedback from @parisk & @akalipetis 

Related: https://github.com/sourcelair/xterm.js/commit/c2aa0d75ec210d50348051492365241f39a884cd

## Details
- Browser and browser version: Chrome
- OS version: Ubuntu 16.04
- xterm.js version: ecfa44b0e8e5ebd410b330ce2b582a3adee67cc2

**Comment by parisk** [comment]
👍  `xterm.setOption('key', `value`)` sounds great.

Also sounds like a good idea to deprecate `xterm.cursorBlink` and other top-level options and force them all to be under the `options` namespace. What do you think?

**Comment by Tyriar** [comment]
@parisk can you elaborate a little on what you mean by options namespace? Specifically how do you set "default" options to be applied to all terminals created and how do you set options specific to terminal (my proposal?)?

**Comment by parisk** [comment]
Sure. In order to avoid bike shedding and getting out of scope though, let me state first:

**I am totally 👍  for your implementation proposal**.

Now in addition to that, let me explain

> what you mean by options namespace?

Let's take for example the `blink` option. I propose making it available only at `term.options.blink` and not `term.blink` (where `term` is a `Terminal` instance).

> Specifically how do you set "default" options to be applied to all terminals created

We can have a `Terminal._defaultOptions` static attribute that will contain all default options and then override any values needed with the provided ones in the `options` argument of the `Terminal` constructor.

> how do you set options specific to terminal (my proposal?)?

`xterm.setOption('key', 'value')`, exactly how you proposed it.

**Comment by Tyriar** [comment]
K, just making sure we are forward thinking :smile:
