### ISSUE TITLE
Spinners in console applications make selection difficult

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#318]
From what I can see, spinners like in npm or https://github.com/sindresorhus/elegant-spinner cause the entire viewport to be destroyed and re-rendered. I believe this is why selecting text is difficult when a spinner is active. If the entire viewport is indeed being re-created this certainly wouldn't be good for laptopbattery either.
## Details
- Browser and browser version: VS Code/electron
- OS version: Ubuntu 16.04
- xterm.js version: https://github.com/sourcelair/xterm.js/commit/8a124d0b355f6aa34448a879787ea169e236f660
### Steps to reproduce
1. Clone vscode
2. Run ./scripts/npm.sh install --arch=x64
3. Try selecting text in the terminal

**Comment by parisk** [comment]
I think the issue might be here: https://github.com/sourcelair/xterm.js/blob/master/src/xterm.js#L1075.

If this is a "big refresh", then xterm.js removes all rows from the DOM for faster calculations and this messes up with selections.

I am not sure what could be the best solution here. Three things come in mind:

1. Smartly update the DOM contents of the terminal in order to avoid messing up with selection
2. Restoring selection programmatically after a refresh (which might feel patchy for the user)
3. Implement virtual selection #207

While **3.** needs the most effort to get right, I guess that it is the best and most future-proof solution.

**Comment by Tyriar** [comment]
Well if we can shift the elements upwards without removing the elements from `.xterm-rows` (1.) and the selection is retained then this would be an ideal step before 3.

**Comment by akalipetis** [comment]
We could also use HTML fragments and partially updating them. This would be a nice idea too IMO.

After a quick Google search I found this one: https://github.com/fiduswriter/diffDOM

**Comment by Tyriar** [comment]
Duplicate https://github.com/sourcelair/xterm.js/issues/468

**Comment by Tyriar** [comment]
Fixed in https://github.com/sourcelair/xterm.js/pull/670
