### ISSUE TITLE
Can not input on Safari

### ISSUE THREAD

**Issue by tsl0922** [sourcelair/xterm.js#346]
Can not input on safari, but works fine on Chrome.

## Details

- Browser version : Safari 10.0.1 (12602.2.14.0.7)
- OS version: macOS Sierra 10.12.1 (16B2555)
- xterm.js version: master (2cba2ff3d4dc545d10efcc2cc040b150a9bb5685)

### Steps to reproduce

1. clone source code from github
2. `npm install` then `npm start`
3. open http://localhost:3000 on Safari
4. input some char, nothing displayed back

This may not always happen, It seems to be something with the input focus.

**Comment by parisk** [comment]
This could be the WebSocket closing. Could you please try refreshing the window and us know if it works after refreshing?

**Comment by tsl0922** [comment]
Refresh doesn't work, it seems not related to websocket, I can input a char by clicking on the cursor and type quickly.

I'm trying to port ttyd from hterm to xterm.js (https://github.com/tsl0922/ttyd/pull/22), can't input on safari, too.

**Comment by parisk** [comment]
Just tried this out and works 👍  for me.

Can you try in a private window please? It might be an extension / addon issue.

**Comment by tsl0922** [comment]
Tried in a private window, not work, then removed all the safari extension, not work too.

**Comment by parisk** [comment]
🆒 . Do you get any console logs/errors?

Also can you please:

1. make a test by binding to the [`keydown`](http://xtermjs.org/docs/api/Terminal/#keydown) event and see if keystrokes are being captured properly
2. take a look at the websocket frames sent and see if the proper character sequences are being sent to the back-end?

**Comment by tsl0922** [comment]
Hi, @parisk 

I can confirm the key event not captured properly, this is my test code (`demo/main.js`), nothing logged when I type.

```js
function runRealTerminal() {
  term.attach(socket);
  term._initialized = true;
  term.on("keydown", function(e){
    console.log(e);
  });
  term.on("key", function(key, e){
    console.log(key, e);
  });
}
```

If I click the terminal with mouse and input quickly, key event can be captured, but only one click one char.

**Comment by tsl0922** [comment]
Hi, again.

I've resolved this issue by clearing the browser cache from safari's developer menu. Don't know why this helps, but thanks for your help!

**Comment by parisk** [comment]
🆒  happy it worked out at last!

**Comment by achimnol** [comment]
I have faced the same problem. Cache clearing didn't work for me, but I found that manually giving focus to the cursor by click the white rectangle by mouse or dragging some rows in the terminal while typing allows me to type something. Without those, I have to press multiple keys within a short time to ensure some of them to be typed. Interestingly, Korean IME works fine! 😮 

On other browsers, I got mixed results, so here I list them below:

 * Safari (10.0.3)
   - 🇺🇸 : ❌ need to keep focus by clicking cursor or dragging the terminal rows simultaneously while typing, otherwise each keystroke is mostly (but not all if I type fast) ignored
   - 🇰🇷 :  ✅ works well
 * Chrome (56.0.2924.87)
   - 🇺🇸 : ✅ works well
   - 🇰🇷 : ❌ does not work (only a space is typed after composition)
 * Firefox (51.0.1)
   - 🇺🇸 : ❌ every character is duplicated
   - 🇰🇷 : ✅ works well

My environment: MacBook Pro mid-2015 15" with macOS Sierra 10.12.3
