### ISSUE TITLE
cursor blinking doesn't work for subsequently created terminals 

### ISSUE THREAD

**Issue by meganrogge** [sourcelair/xterm.js#3517]
because cursorBlinkManager is disposed of but not re-instantiated when a terminal is focused

https://github.com/microsoft/vscode/issues/131446#issuecomment-938219390

**Comment by meganrogge** [comment]
the CursorRenderLayers look pretty much the same - an exception to that is the working one (non-webgl) has this function:

https://github.com/meganrogge/xterm.js/blob/8c94980315076e9c833b27fc3f8aff2bd7c32f67/src/browser/renderer/CursorRenderLayer.ts#L61-L67

**Comment by jerch** [comment]
This looks like a renderer lifecycling issue to me: `CursorBlinkStateManager` gets only created in `onOptionsChanged()` in both renderer cases (canvas vs webgl), but other than the canvas renderer (which exists on the terminal from early bootstrapping), the webgl renderer gets attached late from the addon. By that time the options already got "changed", thus the webgl path never gets that initial "isBlinking" state via `onOptionsChanged()`.

Hacky solution: Re-fire an options changed with `isBlinking` on a renderer change.
Prolly better solution: Init blinking state explicitly durig ctor phase from `optionsService`, instead of relying on proper `onOptionsChanged()` bubbling.

**Comment by Tyriar** [comment]
Initializing it during renderer init seems like the right fix, I think we should keep onOptionsChanged to only get called when the options actually change so we're not doing extra work when creating the renderer.
