### ISSUE TITLE
How to override escape sequence

### ISSUE THREAD

**Issue by scragg0x** [sourcelair/xterm.js#395]
I'm trying to change the behavior of backspace and use `\x08` as the default.  Ideally I would like to have this configurable at run time.

I tried to make use of `customKeydownHandler` and check for backspace and return false and write to term like the following:

```
var term = new Terminal();
term.attachCustomKeydownHandler((ev) => {
        if (ev.keyCode === 8) {
           term.write('\x08');
           return false;
         }
});
```

Is `term.write` equivalent to a keyDown event? I could not create a synthetic Keyboard event due to constraints in the browser.

**Comment by bottleofwater** [comment]
The `term.write` function prints something on the terminal. You (probably) don't want to print anything, but rather send `\x08` to the current application. To do so, use `term.send` (it seems to be undocumented, so it probably isn't a super idea).

**Comment by scragg0x** [comment]
@bottleofwater Thanks for the feedback, I will try it and and let you know how it goes.

**Comment by parisk** [comment]
Hi @scragg0x,

@bottleofwater is partly right (thanks for replying though @bottleofwater 🙂 ), but ⚠️  **you should not use `term.send` as it's not part of the public API** ⚠️  .

Indeed though you do not want to write to the terminal, but send the sequence to the back-end application.

Now chances are you are either communicating with the back-end app via WebSockets. If that's true, I guess all you have to do is send `\x08` to the socket (possibly encapsulate it in your data format, if using any).

If you are using xterm.js in Electron with native Node processes. then just send `\x08` to the process' stdin.

Closing this issue, since it's not an issue of xterm.js, but feel free to continue the discussion here or [on Gitter](https://gitter.im/sourcelair/xterm.js) to get some help with getting your app working!
