### ISSUE TITLE
Make all files ES2015 modules

### ISSUE THREAD

**Issue by parisk** [sourcelair/xterm.js#47]
We could change all files to ES2015 modules. This will help simplify the code base which takes care of commonjs, amd and plain browser environments.

I assume though that if we decide to move on with this it would be a good idea to provide prebuilt files for amd, commonjs and plain browser environment.

**Comment by timotius02** [comment]
Have there been any work on this?

**Comment by parisk** [comment]
Hi @timotius02, no work yet on this. I guess this will start after the release of v1.0.

Do you have any use cases for this right now?

You can already import xterm.js and its add-ons as CommonJS (Node.js-like) and RequireJS module.

**Comment by timotius02** [comment]
Yes I know you can and I'm already doing so. The problem is that the way the project is structured, especially in regards to the addons, require a bit of tinkering. I had hoped I could have just imported the addons separately or easily apply it as some sort of decorator

I'm currently trying to build a React layer on top of xterm to use for [Deco IDE](https://github.com/decosoftware/deco-ide).

**Comment by parisk** [comment]
Hi @timotius02, so your actual issue is that the xterm add-ons require xterm.js itself to works?

**Comment by Tyriar** [comment]
@timotius02 would something like this solve your problem? https://github.com/sourcelair/xterm.js/issues/96

**Comment by parisk** [comment]
@timotius02 does the addon loader attached to #125 solve your issue?

**Comment by timotius02** [comment]
Yep the Addon Loader looks like it will do, although I ended up making my own fix for it. Will try it out as soon as I can.

**Comment by parisk** [comment]
We laid the ground for this in #251 and the first modules have already been extracted. Closing.
