### ISSUE TITLE
Use React in order to render the terminal

### ISSUE THREAD

**Issue by parisk** [sourcelair/xterm.js#48]
We could use [React](http://facebook.github.io/react/) in order to render the terminal.

I guess that we could take advantage of React's Virtual DOM to minify the number of DOM mutations needed when updating the terminal.

We should have in mind though that such a change will dramatically increase the payload of the library.

**Comment by rgbkrk** [comment]
Glad you're all thinking about this and maintaining a fork of term.js.

**Comment by parisk** [comment]
Thanks @rgbkrk!

Do you have any specific use case for this in an application of yours?

Also we always welcome contributions from outside contributors, if you would like to carry this out yourself or in conjunction with us.

**Comment by rgbkrk** [comment]
We use term.js in the ipython / jupyter notebook (as a separate app). @takluyver has been the big developer on that end, writing [terminado](https://github.com/takluyver/terminado) to be the Tornado-backed server for a term.js frontend.

As for my current work, I've been working with some folks on a desktop app of the notebook, called [nteract](https://github.com/nteract/nteract). I expect people to use their native terminal instead of needing a terminal there. What I am interested in right now though is handling text that has ANSI escape codes successfully in the frontend. We certainly have part of that with [`ansi-to-react`](https://github.com/nteract/ansi-to-react). It only handles color escape codes though.

/cc @IonicaBizau who has been working on an Electron app with a terminal called [magnesium](https://github.com/IonicaBizau/magnesium).

**Comment by rgbkrk** [comment]
Sample cell output from nteract (running a Python kernel):

<img width="541" alt="screenshot 2016-03-20 09 35 28" src="https://cloud.githubusercontent.com/assets/836375/13906455/a6b947b2-eeac-11e5-9f19-3c34fcbcd266.png">

**Comment by takluyver** [comment]
Thanks for the ping, it's interesting to see there's an active fork of term.js. @rgbkrk are you evaluating a potential switch to this?

**Comment by rgbkrk** [comment]
I'm currently evaluating terminal emulators in general right now and learning how it all works. Soon I'll be refactoring term.js for my own understanding (and export as commonjs for webpack/browserify consumption).

Other than that, planning on handling Jupyter message protocol streams with support for more escape codes than just color.

**Comment by parisk** [comment]
At the moment xterm.js (like term.js) already provides ANSI character support and works also with curses-based applications.

I guess that if we ansi-to-react was modified in order to support curses applications as well, we could make a full switch to React rendering and this could be used both in our product ([SourceLair](https://www.sourcelair.com/home)) and in yours.

Is such a scenario open for you? In any case we will move with starting developing the react rendering within the next weeks.

**P.S.** Xterm.js already works as a CommonJS and RequireJS module.

**Comment by rgbkrk** [comment]
ANSI to react is a static display. It converts output text to rendered text, just like the ansi-to-html package. 

I'm happy to use and contribute to xterm.js over here.

What I meant by exporting more is that I'd like to break more out of the Terminal class, mostly in terms of splitting the view and the model (I want to use the model elsewhere).

**Comment by parisk** [comment]
Okay, I think I got the point of this. I think the best way to go is open a new branch straight away and start  reworking the [`refresh`](https://github.com/sourcelair/xterm.js/blob/f53f573/src/xterm.js#L976) method (which takes care of the rendering) to see if it works out and if it performs better with React + ansi-to-react.

@rgbkrk we could work together on this if you would like so.

Also, do you know what could we do with ansi-to-react to make the terminal work with Vim and other curses-based applications?

**Comment by rgbkrk** [comment]
ansi-to-react is only for static content - no cursors, etc. I wouldn't rely on it - it's only for quick display. Still work to do to make it implement the full terminal state machine. My next steps were going to be to refactor term.js to break it up a bit and tearing out code that can currently be supplemented by a bundler (the EventEmitter for instance can be implemented by browserify or webpack).

**Comment by parisk** [comment]
Correct me if I am wrong, but I do not think that cursor handling is in ansi-to-react's scope, so you could avoid dealing with this at all. From my understanding ansi-to-react deals only with drawing the terminal output (except for the cursor), which usually contains ANSI chars, into a div.

Also, do you have any next steps for it? I can't see any open issues or PRs there.

Last, can you give me some more context on how could Browserify replace the EventEmitter implementation?

**Comment by rgbkrk** [comment]
> Correct me if I am wrong, but I do not think that cursor handling is in ansi-to-react's scope, so you could avoid dealing with this at all. From my understanding ansi-to-react deals only with drawing the terminal output (except for the cursor), which usually contains ANSI chars, into a div.

It's correct that we don't want to handle user context of cursor or mouse movement. What we do want to handle is reducing:

<img width="775" alt="screenshot 2016-03-29 09 16 24" src="https://cloud.githubusercontent.com/assets/836375/14117087/d8272f02-f597-11e5-849d-386c985fbfab.png">

to this:

<img width="779" alt="screenshot 2016-03-29 10 20 57" src="https://cloud.githubusercontent.com/assets/836375/14117094/e1177216-f597-11e5-848c-2549c8ecc56e.png">


> Also, do you have any next steps for it? I can't see any open issues or PRs there.

Right now we're in a learning stage with respect to the terminal emulator model. I should probably open an issue about handling cursor movement and erasure codes, since it's largely just been scattered notes.

> Last, can you give me some more context on how could Browserify replace the EventEmitter implementation?

Assuming that it's compatible, both browserify and webpack will turn

```
const EventEmitter = require('events');
```

Into an appropriate version of `EventEmitter` for the web.

**Comment by rgbkrk** [comment]
Anyways, I think I've hijacked this discussion. I'll write up some issues on what we need in ansi-to-react while also learning from and contributing to these various term-js forks.
