### ISSUE TITLE
Multiple terminals don't work correctly

### ISSUE THREAD

**Issue by jjuu** [sourcelair/xterm.js#496]
## Details
- Browser and browser version: Chrome
- OS version: Windows 7
- xterm.js version: latest

### Steps to reproduce

I use bootstrap tab to support multiple terminals in one page.
But the second terminal connects but cannot input anything.

The first terminal:
```
******************************************
******   Welcome to the Cloud Lab   ******
******************************************
root@ls2000:~#  口

```

The second terminal:
```
******************************************
******   Welcome to the Cloud Lab   ******
******************************************

口
```

Here's my code below:
```
function make_console_terminal(board_name) {
	var term = new Terminal({
		cols: 80,
		rows: 26,
		screenKeys: true
	}),
	url = 'ws://{{ bf_addr }}/ws?api_token=1111&board=' + board_name;
	var socket = new WebSocket(url);
	term.open(document.getElementById(board_name + '_container'));
	term.on('data', function (data) {
		socket.send(data);
	});

	socket.onmessage = function (e) {
		term.write(e.data);
	};

	return {
		terminal: term,
		socket: socket
	}
}

var boards = ["LS1000", "LS2000"];;
var terminals = {};
for (var _index in boards) {
	var board_name = boards[_index];
	terminals[board_name] = make_console_terminal(board_name);
}


```

**Comment by parisk** [comment]
@jjuu can you put the code in the original issue [into code blocks](https://guides.github.com/features/mastering-markdown/) in order to be more readable?

In SourceLair we use xterm.js to create multiple terminals and everything works fine for us, so I am not sure what the problem might be here.

Can you dig a little bit deeper into that and let us know if the problem is in the socket or in input handling?
