### ISSUE TITLE
Resizing the terminal while in the alt buffer will break the normal buffer

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#510]
Downstream issue https://github.com/Microsoft/vscode/issues/19385

### Steps to reproduce

- Have some output in the terminal like from `ls -l`
- Open vim
- `:q`
- You can still see the output from `ls`, good
- Open vim again
- Resize the terminal
- `:q`
- The vim text is still on screen, and I can't scroll to see the output from `ls`.

**Comment by Tyriar** [comment]
This is not as trivial as it looks. It's happening because the normal buffer is cleared in resize, this is done because without doing this it doesn't get resized which causes a lot of issues if the rows were reduced.

**Comment by mofux** [comment]
I noticed this when I was looking through the code the other day. When the alt screen buffer is created, the normal screen buffer is backed up to `terminal.normal`, but `terminal.normal` never seems to get modified, not even on resize. When we switch back to the normal buffer, the `terminal.normal` backup is restored.

[InputHandler.ts - creating the alternate buffer](https://github.com/sourcelair/xterm.js/blob/742d28fcc33f476a9de7869d47dea1d74d16c916/src/InputHandler.ts#L935)
[InputHandler.ts - restoring the normal buffer](https://github.com/sourcelair/xterm.js/blob/742d28fcc33f476a9de7869d47dea1d74d16c916/src/InputHandler.ts#L1114)

But still, given the way the alt buffer is replaced by normal buffer, how can there still be any content from the alt buffer making its way back to the normal buffer? I assume this happens because we do not call `terminal.reset()` before restoring the normal buffer (notice `terminal.reset()` is called when the alt screen buffer is created). Is there a reason why `terminal.reset()` is not called?

**Comment by Tyriar** [comment]
`normal = null` means that the alt buffer becomes the normal buffer, so nothing happens when you switch back to the normal buffer after exiting vim.  We probably want to call resize again after the normal buffer is switched in, reworking resize so it doesn't break when we call it again.
