### ISSUE TITLE
CJK characters are not treated as double width chars

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#62]
See https://github.com/chjj/term.js/issues/96

![image](https://cloud.githubusercontent.com/assets/2193314/15738068/539d8c82-285e-11e6-91ce-b839db904383.png)

vs gnome-terminal:

![image](https://cloud.githubusercontent.com/assets/2193314/15738083/67542448-285e-11e6-83be-6db1b670e607.png)

Notice the characters are exactly 2 ascii characters in width

**Comment by parisk** [comment]
Thanks for reporting. Will take a look at this along with the rest international character issues.

**Comment by parisk** [comment]
Seems like the weird line break is actually the div overflowing. This indeed happens because these are double byte characters, the terminal ignores this fact and counts them as single-byte ones.

Working on a fix.

## Screenshot
![image](https://cloud.githubusercontent.com/assets/1188592/15852933/afdcc7a0-2cab-11e6-961a-0ae79cfe399e.png)

**Comment by jerch** [comment]
@parisk To support this you gonna have to include the wcwidth calculation for any Unicode codepoint (see `man wcwidth`) and adjust the taken space for fullwidth characters to 2 terminal cells (terminals are based on the idea that a single cell can hold one halfwidth character since all western characters are halfwidth).
Problem with Javascript and Unicode is - it is a total mess with the UTF-16 encoding (surrogates) and very expensive to calculate. This gets even more complicated if you plan to support stackable combining characters (wcwidth will report a width of zero for those). This might be easier to implement once the Unicode functions with real codepoints are widely adapted by the JS engines.
I tried to implement this according to the Unicode spec but well - it ended up as a total code mess in my own terminal emulator.

**Comment by jerch** [comment]
I had a look at your line at cell abstraction - this is pretty much the same I did in my emulator. If you like I can extend your isWide and write functions with the wcwidth stuff in a PR.
Another problem is the rendering with Unicode. For higher BMP or non BMP codepoints the fonts might differ in the glyph width from wcwidth (if they have that glyph at all). You are likely to need a CSS class fixing misaligned glyphs into place to keep the output a well formed cell grid.

**Comment by parisk** [comment]
Interesting. Do you believe that this could be handy? http://code.woong.org/wcwidth.js

**Comment by jerch** [comment]
yes, it should do the trick, though it is not 100% xterm compatible (xterm uses a slightly different version of it). If xterm compatibility is a major concern for xterm.js, we'd have to strip the lookup tables from their sources.

**Comment by Tyriar** [comment]
You can look at a solution to this here https://github.com/chjj/term.js/pull/97

**Comment by jerch** [comment]
That seems to work for BMP fullwidth characters. Surrogates are still failing in width and cursor positioning as you can test with these characters: 𝟙𝟚𝟛𝟜𝟝𝟞𝟟𝟠𝟡

**Comment by parisk** [comment]
Closed in #144.
