### ISSUE TITLE
Why is xterm.js sending OpCode(-1)

### ISSUE THREAD

**Issue by atedja** [sourcelair/xterm.js#631]
Apologize in advance if this is not the right channel to ask questions.  I am building an xterm.js to a docker tty and all works well except when running vim.  I am wondering why xterm.js sent opcode close to disconnect as soon as `vim` is executed.

The sequence of the connections from Firefox websocket sniffer looks like this:
`>> v`
`<< v`
`>> i`
`<< i`
`>> m`
`<< m`
`>> \r`
`<< \r\n`
`>> opcode close`

Firefox reported opcode 8 with payload `ï`, while Chrome reported payload `(Opcode -1)` with length 39 bytes (not sure where the rest went), but they both close the session.

xterm version 2.4.0

**Comment by parisk** [comment]
Hi @atedja. This seems to be an issue with your back-end application, since xterm.js is a front-end only terminal emulator.

The best place to ask implementation questions is our Gitter channel: https://gitter.im/sourcelair/xterm.js.

We keep the GitHub issues only for xterm.js code base issues right now, so I will be closing this.

Please feel free to reach out [on Gitter](https://gitter.im/sourcelair/xterm.js) for help 😄 !

**Comment by atedja** [comment]
My backend actually reported unexpected EOF from xterm.js, so xterm.js is initiating the closure.  Anyway, I am going to gitter for more info.

Thank you for the help!
