### ISSUE TITLE
ctrl+left/right should jump the cursor over words in the input

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#65]
It just moves the cursor a single character currently.

**Comment by parisk** [comment]
Did you notice that happening in the demo page of xterm.js? If yes, the reason behind this is that it is not hooked to a back-end terminal in order to implement these movements.

Since xterm.js is just a front-end terminal emulator, it will need a back-end in order to send the control characters and get the cursor movements back.

Giving it a try in a more complete example, like www.sourcelair.com, which utilizes xterm.js and hooks it to a Linux terminal in the back-end, should work actually.

**Comment by Tyriar** [comment]
This was using https://www.sourcelair.com (bash)

**Comment by parisk** [comment]
Thanks for letting me know. Will take a deeper look into that.
