### ISSUE TITLE
Fit mode leaves blank space at the bottom if half row

### ISSUE THREAD

**Issue by yunyu** [sourcelair/xterm.js#762]
It's a bit hard to describe the issue in words, so here's a screen recording:

https://my.mixtape.moe/ibqcjc.mp4

I was wondering if it's possible to make the drawn area stretch to the bottom and just not display anything on the blank space, while the scrollbar matches the height of the fitted element. My current workaround is to make the fitted element have a black background, which works but causes the scrollbar to look strange:

![](https://i.imgur.com/r0Qnks8.png)

**Comment by Tyriar** [comment]
@yunyu there has to be some blank space at either the bottom or the top of the terminal because the size is exactly `number_of_rows *  height of character`. You can probably change the background color of that part by using a custom style.

**Comment by yunyu** [comment]
@Tyriar I did in my second example, but the scrollbar looks strange. Can you make it so that the terminal extends that area?

**Comment by Tyriar** [comment]
I don't think that would be a good idea because that would look weird in other use cases (why does the scroll bar extend beyond what it's scrolling), but more importantly it would add a lot more complexity to the scrollbar. Currently it's sized exactly to the size of the viewport and there is a "scrollable DOM element" inside it which is the size of the terminal.

You could try styling the scroll bar, it's well supported now and it can look really good when done right. You can also align to the bottom which will probably look better. For example:

![image](https://user-images.githubusercontent.com/2193314/27923303-cc5f7220-6232-11e7-86a0-bd791a6238b7.png)

**Comment by yunyu** [comment]
I ended up doing that, but unfortunately it doesn't work in Firefox or Edge. Would it be safe to adjust the bottom padding of the background after I call fit()?

**Comment by Tyriar** [comment]
@yunyu you should be able to position the terminal container (what you called `Terminal.open` with) however you want (`display: flex`, `position: absolute`, etc.). You can also look at the [fit logic](https://github.com/sourcelair/xterm.js/blob/479fb0e782359165091bd2e8970ac50c6695aa74/src/addons/fit/fit.js#L73) and write your own logic to fit it correctly which is what a lot of consumers do (including myself).

**Comment by yunyu** [comment]
I guess that won't work then, I have a fixed height navigation bar and the terminal takes up the entire visible viewport. Oh well, that's unfortunate, thanks anyways.

**Comment by jtbandes** [comment]
> you should be able to position the terminal container (what you called `Terminal.open` with) however you want (`display: flex`, `position: absolute`, etc.).

In 5.6.0-beta, it seems like expanding the size of the container with `flex-grow: 1` and `padding: 4px` can lead to a black border showing. This is because the `.xterm-viewport` has a black background (not using the theme color) and `.xterm-scrollable-element` does not automatically fit to its parent:

<img width="561" alt="image" src="https://github.com/user-attachments/assets/0638711b-5816-4ee3-9581-832f57a0cdc7">

Any tips for how to do this properly nowadays?

**Comment by Tyriar** [comment]
@jtbandes in vscode I think we size `.xterm` manually via `position:absolute`/`right` and don't use the fit addon:

![Image](https://github.com/user-attachments/assets/4abd8a16-d2b2-495b-b69c-9f0f3c850e5b)

![Image](https://github.com/user-attachments/assets/44756f46-833a-40ad-8c0c-4cab70e049db)

That means we need to implement logic similar to fit there:

https://github.com/microsoft/vscode/blob/cb4076e563719dc2b29761f8239cbcf4de585d49/src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts#L850-L870

**Comment by jtbandes** [comment]
@Tyriar thanks for the tip. If you do this, is there a way to adjust the scrollbar position so it takes the full height, while leaving some padding around the actual terminal content?

**Comment by jtbandes** [comment]
It seems like the FitAddon is [designed to handle padding on `.xterm`](https://github.com/xtermjs/xterm.js/blob/master/addons/addon-fit/src/FitAddon.ts#L76), however this leads to the scrollbar & overview ruler being misaligned (scrollbar moves because of padding, while overview ruler does not).
