### ISSUE TITLE
Loading Addons in Angular 2 / Typescript

### ISSUE THREAD

**Issue by DerekTBrown** [sourcelair/xterm.js#792]
I am not sure how to import the addons packages when using Angular 2 / Typescript.  The solution I came up with is rather inelegant:

```Typescript
// Import Angular
	import { Component } from '@angular/core';

// Import Xterm
        import * as Terminal from 'xterm/dist/xterm';
	import style from 'xterm/dist/xterm.css';
	import 'xterm/dist/addons/fit/fit.js';

// Export Data Interface
  @Component({
    selector: 'terminal',
    template: '<div id="terminal" #terminal></div>',
    styles: [ style ]
  })

  export default class TerminalView {
		@ViewChild('terminal') container : ElementRef;
		private xterm : Terminal;

		ngOnInit(){
			this.xterm = new Terminal();
			this.xterm.open(this.container.nativeElement);
			this.xterm.fit();
		}

  }

```

**Comment by parisk** [comment]
@DerekTBrown feel free to continue the discussion here or posting a question in the [`xtermjs` StackOverflow tag](https://stackoverflow.com/tags/xtermjs/). 

I will be closing this issue since it does not have to do with xterm.js itself, but with how you can use it in a particular context.

I am not sure what inelegant means in your case as I have no experience with Angular, but you can try using the [`loadAddon`](https://xtermjs.org/docs/api/terminal/#loadaddonaddon-callback) method which is the suggested way of consuming xterm.js.

**Comment by parisk** [comment]
@DerekTBrown also, if you find a more elegant way to consume xterm.js with Angular, please let us know and we will add it in [our documentation website](https://xtermjs.org/docs) 😄 .

**Comment by GavinSong123** [comment]
@DerekTBrown I want to use xterm in angular2. But the ```private term: Terminal;``` has error that ```Cannot find name 'Terminal'.```.

**Comment by DerekTBrown** [comment]
@GavinSong123 did you install the typings?  If not, `npm install --save-dev @types/xterm`

**Comment by DerekTBrown** [comment]
@parisk I think the easy solution would be to export the typings from this project directly into the `@types/xterm` package (which is in DefinitelyTyped).

**Comment by Tyriar** [comment]
@DerekTBrown https://github.com/sourcelair/xterm.js/issues/335 is inching closer and closer to done. Once that's complete typings will be shipped with the module so it should all just work.

**Comment by GavinSong123** [comment]
@DerekTBrown Yes, I had installed ```xterm```. And I solved it by defining ```private term: any```. It also worked.
