### ISSUE TITLE
Emojis offset the selection by 1 per character

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#826]
VS Code issue: https://github.com/Microsoft/vscode/issues/31694

![28740974-366458be-7450-11e7-8c28-569221ad5578](https://user-images.githubusercontent.com/2193314/28787154-40436894-75d0-11e7-91cf-97742926f3ff.gif)

**Comment by rmunn** [comment]
Reposting [my comment from the VS Code bug](https://github.com/Microsoft/vscode/issues/31694#issuecomment-318990449) over here so xterm don't have to click through to see it (and also expanding it slightly):

I suspect the :beer: emoji in the terminal prompt is probably responsible for this, and that this would be reproducible by having any emoji (or any other character from one of the supplimentary Unicode planes) in your prompt. If what I suspect is correct, changing your prompt to contain two beer emojis (i.e., :beer::beer:) would cause the selection to be off by two characters rather than one, because some part of the selection code is counting code units when it should be counting codepoints, or vice versa.

For anyone not aware of the difference between code units and code points: a code point is a single Unicode character, like [U+1F37A](http://www.fileformat.info/info/unicode/char/1f37a/index.htm). In UTF-8, that character is represented as the sequence `0xF0 0x9F 0x8D 0xBA`. In UTF-16, it's represented by the surrogate pair `0xD83C 0xDF7A`. A "code unit" is the individual units of those representations; so `0xF0` is a code unit in UTF-8, and `0xD83C` is a code unit in UTF-16. Code units will *always be the same size* in any given Unicode encoding (8 bits in UTF-8, 16 bits in UTF-16). But code points will *vary in size*: U+1F37A will not be the same number of bytes as U+0020. People working in UTF-8 are constantly aware of this, but people who work in UTF-16 often forget this point since so many UTF-16 codepoints are a single code unit long.

**Comment by DvStephen** [comment]
Not sure if this is related but in general surrogate pairs seem to cause a variety of issues:

![image](https://user-images.githubusercontent.com/31885375/32231026-6ef8843e-be4c-11e7-928a-7c45aa3a153b.png)

This is the source:

![image](https://user-images.githubusercontent.com/31885375/32231012-61b9b572-be4c-11e7-901f-1704543664ff.png)

Note that the first space after the 🚀 is consumed and the link underline (plus hitbox) are offset.

Adding more rockets gives:

![image](https://user-images.githubusercontent.com/31885375/32231136-b9826376-be4c-11e7-8da7-8a225584dc88.png)

Which shows the issue compounds, and also that the rockets will overlap the subsequent character.

FWIW:

![image](https://user-images.githubusercontent.com/31885375/32231316-26d4f894-be4d-11e7-8dbd-c7b4a0259022.png)

**Comment by Tyriar** [comment]
@DvStephen are you using v2.9.2 from npm? I think these issues are fixed in the v3 branch and this can be closed off.
