### ISSUE TITLE
xterm.js on mobile browser

### ISSUE THREAD

**Issue by Tilesentik** [sourcelair/xterm.js#945]
## Details
- Browser and browser version: chrome
- OS version: ios 8
- xterm.js version: 2.9.0

### Steps to reproduce
I have xterm.js running on a web server, and when I connect to it with my phone i am unable to type in the console. Is there any way to fix this.

**Comment by parisk** [comment]
@Tilesentik thanks for reporting this. Can you reproduce this issue when viewing the xterm.js demo in your mobile also?

**Comment by Tilesentik** [comment]
I'm not sure what your asking

**Comment by parisk** [comment]
Can you please do the following:

1. Run the [xterm.js demo](https://github.com/sourcelair/xterm.js/tree/master/demo) in a publicly accessible URL
2. Open this URL in your mobile browser

Are you still unable to type into the console?

(Or is this what you are already doing?)

**Comment by Tilesentik** [comment]
closed by mistake. I see you need to set the platform. How would you do that in javascript rather that typescript.

**Comment by gbrault** [comment]
@parisk propose the right experiment and on my samsung galaxy a5 android 8.0.0 mobile it doesn't work: no keys except cr is taken into account.
Do you think this can be fixed?

**Comment by parisk** [comment]
@gbrault I am no longer contributing to the development of xterm.js, as I don't have any available time in my day for it.

I guess this is an issue with your device though, since Azure Shell (which uses xterm.js) works fine on my device.

Also, you can [open an issue](https://github.com/xtermjs/xterm.js/issues/new/choose) to ask about mobile support and share as much details as possible about the issue you ran into. The team behind xterm.js is amazing and will help find out if this is indeed an issue with your device or something that needs to be fixed in xterm.js' xodebase.
